THIS HW IS COMPLETE AND SUBMITTED 12/12 Points on Attempt 2

In [45]:
import numpy as np

In [189]:
x = np.array([-1.6])

for j in range (0, 1000):
    fx = x[j]*np.sin(3*x[j]) - np.exp(x[j])
    
    x = np.append(x, x[j] - ((x[j]*np.sin(3*x[j]) - np.exp(x[j])) / ((3*x[j])*np.cos(3*x[j]) + np.sin(3*x[j]) - np.exp(x[j]))))
    
    if (abs(fx) < 1e-6):
        break
    
    
###

x1 = -0.7 # fx1 is +
x2 = -0.4 # fx2 -is -
xm = np.array([])

for k in range(0,100):
    xc = (x1+x2)/2
    xm = np.append(xm,[xc])
    
    fxc = xc*np.sin(3*xc) - np.exp(xc)

    if (fxc < 0):
        x2 = xc
    else:
        x1 = xc
    
    if (abs(fxc) < 1e-6):
        break

A1 = x
A2 = xm
A3 = np.array([j+1, xm.size])

display(A1)
display(A2)
display(A3)

np.save('A1.npy', A1)
np.save('A2.npy', A2)
np.save('A3.npy', A3)

array([-1.6       ,  3.19799514,  2.46440244,  1.2035359 ,  0.65020146,
       -0.11692334, -0.66052349, -0.52192654, -0.56655274, -0.57074658,
       -0.57078962, -0.57078962])

array([-0.55      , -0.625     , -0.5875    , -0.56875   , -0.578125  ,
       -0.5734375 , -0.57109375, -0.56992188, -0.57050781, -0.57080078,
       -0.5706543 , -0.57072754, -0.57076416, -0.57078247, -0.57079163,
       -0.57078705, -0.57078934])

array([11, 17])

In [191]:
A = np.array([[1,2], [-1,1]])
B = np.array([[2,0],[0,2]])
C = np.array([[2,0,-3],[0,0,-1]])
D = np.array([[1,2],[2,3],[-1,0]])

x = np.array([[1],[0]])
y = np.array([[0],[1]])
z = np.array([[1],[2], [-1]])

A4 = A + B

T5 = 3*x-4*y
A5 = np.reshape(T5.T, ((T5.shape)[0], ))

T6 = np.dot(A,x)
A6 = np.reshape(T6.T, ((T6.shape)[0], ))

T7 = np.dot(B ,(x-y))
A7 = np.reshape(T7.T, ((T7.shape)[0], ))

T8 = np.dot(D,x)
A8 = np.reshape(T8.T, ((T8.shape)[0], ))

T9 = np.dot(D,y) + z
A9 = np.reshape(T9.T, ((T9.shape)[0], ))

A10 = np.dot(A,B)
A11 = np.dot(B,C)
A12 = np.dot(C,D)

print(A5.shape)
print(A6.shape)
print(A7.shape)
print(A8.shape)
print(A9.shape)

np.save('A4.npy', A4)
np.save('A5.npy', A5)
np.save('A6.npy', A6)
np.save('A7.npy', A7)
np.save('A8.npy', A8)
np.save('A9.npy', A9)
np.save('A10.npy', A10)
np.save('A11.npy', A11)
np.save('A12.npy', A12)

(2,)
(2,)
(2,)
(3,)
(3,)
